::al::I will
::ek::he can
::tl::it will
::nh::in the
::ut::yours truly
::ds::dear sir
::oh::of the
::ndh::and the
::lb::will be
::tuh::to the
::hah::that the
::ou::of you
::ts::it is
::bh::by the
::tos::it was
::am::I am
::uk::you can
::eos::he was
::tuu::to you
::th::at the
::sh::is the
::vb::have been
::asb::has been
::adb::had been
::dm::Dear Madam
::vtu::very truly yours
::uvt::yours very truly
::fh::for the
::uv::you have
::db::would be
::tb::to be
::hs::there is
::kb::can be
::ehh::with the
::os::of his
::may be::mab
::av::I have
::fu::for you
::ndha::and that
::fmh::from the
::efu::if you
::ash::as the
::ohs::of this
::ou::of your
::nr::in our
::hr::there are
::nhs::in this
::oo::of all
